inherit_from: rubocop-todo.yml

AllCops:
  Exclude:
    - !ruby/regexp /\/db\/schema\.rb$/
    - !ruby/regexp /\/vendor\/.*/

# configs clearly to be false

AsciiComments:
  Enabled: false

# configs ambiguously to be false

# Offense count: 2
# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep.
CaseIndentation:
  Enabled: false

